We currently only accept these forms of support but more will come in the future.

Cash Tag --> $CalmCapitalist

If you are unable to support us with these methods you could also boost our Discord server at https://discord.gg/bJmDnPNNT7

If you have issues supporting us or would like to claim your benifits, make a ticket in our Discord server using the 🎫𝗦𝘂𝗽𝗽𝗼𝗿𝘁-𝗧𝗶𝗰𝗸𝗲𝘁 channel under the Support category
and go to the new ticket channel at the top of the channel list and provide the Staff Member with the information on what you need assistance with.
